quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "The secret of getting ahead is getting started. - Mark Twain",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "The only thing standing between you and your dream is the will to try and the belief that it is actually possible. - Joel Brown",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "The future depends on what you do today. - Mahatma Gandhi",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "If you really look closely, most overnight successes took a long time. - Steve Jobs",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "The best revenge is massive success. - Frank Sinatra",
    "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
    "Success is not just about making money. It's about making a difference. - Unknown",
    "The secret to success is to know something nobody else knows. - Aristotle Onassis",
    "Try not to become a person of success, but rather try to become a person of value. - Albert Einstein",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Success is not the result of spontaneous combustion. You must set yourself on fire. - Arnold H. Glasow",
    "Don't be distracted by criticism. Remember, the only taste of success some people get is to take a bite out of you. - Zig Ziglar",
    "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Success is not just about making money. It's about making a difference. - Unknown",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "The secret of success is to know something nobody else knows. - Aristotle Onassis",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "The best revenge is massive success. - Frank Sinatra",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
    "If you really look closely, most overnight successes took a long time. - Steve Jobs",
    "Try not to become a person of success, but rather try to become a person of value. - Albert Einstein",
    "The secret to success is to know something nobody else knows. - Aristotle Onassis",
    "Success is not just about making money. It's about making a difference. - Unknown",
    "The future depends on what you do today. - Mahatma Gandhi",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Success is not the result of spontaneous combustion. You must set yourself on fire. - Arnold H. Glasow",
    "The best revenge is massive success. - Frank Sinatra",
    "Success is not just about making money. It's about making a difference. - Unknown",
    "The secret to success is to know something nobody else knows. - Aristotle Onassis",
    "Try not to become a person of success, but rather try to become a person of value. - Albert Einstein",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
    "If you really look closely, most overnight successes took a long time. - Steve Jobs",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "The best revenge is massive success. - Frank Sinatra",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "The secret of getting ahead is getting started. - Mark Twain",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "The only thing standing between you and your dream is the will to try and the belief that it is actually possible. - Joel Brown",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "The future depends on what you do today. - Mahatma Gandhi",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "If you really look closely, most overnight successes took a long time. - Steve Jobs",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
    "Try not to become a person of success, but rather try to become a person of value. - Albert Einstein",
    "The secret to success is to know something nobody else knows. - Aristotle Onassis",
    "Success is not just about making money. It's about making a difference. - Unknown",
    "The future depends on what you do today. - Mahatma Gandhi",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "The harder you work for something, the greater you'll feel when"
]

a = len(quotes)
print(a)